package com.taxiticket.app;
import android.Manifest; import android.app.Activity; import android.content.*; import android.content.pm.PackageManager; import android.net.Uri; import android.os.*; import android.provider.MediaStore; import android.webkit.*; import android.widget.Toast; import androidx.core.content.FileProvider; import com.google.mlkit.vision.common.InputImage; import com.google.mlkit.vision.text.TextRecognition; import com.google.mlkit.vision.text.TextRecognizer; import com.google.mlkit.vision.text.latin.TextRecognizerOptions; import java.io.*; import java.text.SimpleDateFormat; import java.util.*;
/** Local-only WebView host. */
public class MainActivity extends Activity {
 private static final int FILE_REQUEST=41,CAMERA_PERMISSION=42; private WebView webView; private ValueCallback<Uri[]> fileCallback; private Uri cameraUri; private boolean captureRequested,ocrUnavailable; private TextRecognizer recognizer;
 @Override public void onCreate(Bundle state){super.onCreate(state);try{recognizer=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);}catch(RuntimeException e){ocrUnavailable=true;} webView=new WebView(this);WebSettings s=webView.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);webView.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;captureRequested=p.isCaptureEnabled();if(captureRequested&&Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA},CAMERA_PERMISSION);else launchFileSource();return true;}});setContentView(webView);webView.loadUrl("file:///android_asset/index.html");}
 private void launchFileSource(){if(captureRequested){Intent c=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);if(c.resolveActivity(getPackageManager())!=null)try{File d=new File(getExternalFilesDir(Environment.DIRECTORY_PICTURES),"tickets");if(!d.exists()&&!d.mkdirs())throw new IOException();File f=File.createTempFile("ticket_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date()),".jpg",d);cameraUri=FileProvider.getUriForFile(this,getPackageName()+".fileprovider",f);c.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);c.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);startActivityForResult(c,FILE_REQUEST);return;}catch(IOException|IllegalArgumentException e){Toast.makeText(this,"No se pudo preparar la cámara. Puedes elegir una imagen.",Toast.LENGTH_LONG).show();}}Intent p=new Intent(Intent.ACTION_OPEN_DOCUMENT);p.addCategory(Intent.CATEGORY_OPENABLE);p.setType("image/*");p.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);try{startActivityForResult(p,FILE_REQUEST);}catch(ActivityNotFoundException e){finishFileSelection(null);}}
 @Override public void onRequestPermissionsResult(int r,String[] p,int[] x){super.onRequestPermissionsResult(r,p,x);if(r==CAMERA_PERMISSION){if(x.length>0&&x[0]==PackageManager.PERMISSION_GRANTED)launchFileSource();else finishFileSelection(null);}}
 @Override protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r!=FILE_REQUEST)return;Uri u=result==RESULT_OK?(cameraUri!=null?cameraUri:(data==null?null:data.getData())):null;finishFileSelection(u==null?null:new Uri[]{u});cameraUri=null;if(u!=null)runOcr(u);}
 private void finishFileSelection(Uri[] u){if(fileCallback!=null){fileCallback.onReceiveValue(u);fileCallback=null;}}
 private void runOcr(Uri u){if(ocrUnavailable||recognizer==null){deliverOcr(null,"OCR local no disponible en esta instalación. Puedes completar los campos manualmente.");return;}try{recognizer.process(InputImage.fromFilePath(this,u)).addOnSuccessListener(x->deliverOcr(x.getText(),null)).addOnFailureListener(x->deliverOcr(null,"No se pudo leer esta imagen con el OCR local. Revisa y completa los campos manualmente."));}catch(IOException|RuntimeException e){deliverOcr(null,"No se pudo abrir la imagen para el OCR local. Revisa y completa los campos manualmente.");}}
 private void deliverOcr(String t,String m){if(webView==null)return;String p=org.json.JSONObject.quote(t==null?"":t),e=m==null?"null":org.json.JSONObject.quote(m);runOnUiThread(()->webView.evaluateJavascript("window.onNativeOcrText && window.onNativeOcrText("+p+","+e+");",null));}
 @Override protected void onDestroy(){finishFileSelection(null);if(recognizer!=null)recognizer.close();if(webView!=null)webView.destroy();super.onDestroy();}
}
